<?php

class Pato extends Animal
{
    public function __construct($raza, $nombre)
    {
        parent::__construct(2, $raza, $nombre);
    }
    public function hablar()
    {
        return "Cua Cua";
    }
    public function __toString()
    {
        return "Pato: ".parent::__toString(); // TODO: Change the autogenerated stub
    }

}