<?php

class Perro extends Animal
{
    public function __construct($raza, $nombre)
    {
        parent::__construct(4, $raza, $nombre);
    }
    public function hablar()
    {
        return "Guau";
    }
    public function __toString()
    {
        return "Perro: ".parent::__toString(); // TODO: Change the autogenerated stub
    }
}